# Generated by Django 4.2.3 on 2023-08-06 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(default='0', max_length=100000, verbose_name='title')),
                ('title_en', models.CharField(default='0', max_length=100000, verbose_name='title')),
                ('description_fa', models.TextField(default='0', max_length=10000000, verbose_name='description')),
                ('description_en', models.TextField(default='0', max_length=10000000, verbose_name='description')),
                ('image', models.ImageField(upload_to='Images', verbose_name='image')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SlideShow.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Slide Show',
                'verbose_name_plural': 'Slide Shows',
                'ordering': ['-article__publish'],
            },
        ),
    ]
